version: '1'  # The schema version of this config file

ignore:  # A list of paths or files which Sourcery will ignore.
  - .git
  - env
  - .env
  - .tox
  - node_modules
  - vendor
  - venv
  - .venv
  - ~/.pyenv
  - ~/.rye
  - ~/.vscode
  - .vscode
  - ~/.cache
  - ~/.config
  - ~/.local

rule_settings:
  enable:
    - default
    - inline-improvements  # Suggests inlining variable assignments for better readability and performance
    - function-extraction  # Extracts duplicate functionality into reusable functions
    - list-comprehension   # Converts loops into list comprehensions when appropriate
    - use-with             # Recommends using 'with' statements for handling resources (like files)
    - return-early         # Encourages returning early to avoid deep nesting
    - merge-nested-ifs     # Merges nested if-statements where possible
  disable: []  # A list of rule IDs Sourcery will never suggest.
  rule_types:
    - refactoring
    - suggestion
    - comment
  python_version: '3.9'  # Ensures compatibility with Python 3.9

rules:  # Custom rules for specific cases.
  - id: no-print-statements
    description: Avoid using print statements in test files, use logging instead.
    pattern: '{print($VAR)}'
    language: python
    replacement: |
      logging.info($VAR)
    explanation: Use logging instead of print statements for better control and verbosity in test files.
    paths:
      include:
        - test

  - id: no-explicit-exceptions
    description: Avoid catching base 'Exception', use more specific exceptions instead.
    pattern: '{try: $BODY except Exception as $E: $HANDLER}'
    language: python
    replacement: |
      try:
          $BODY
      except (SpecificError1, SpecificError2) as $E:
          $HANDLER
    explanation: Catch specific exceptions to avoid swallowing important errors.

rule_tags:
  performance:
    - inline-improvements
    - function-extraction
    - list-comprehension

metrics:
  quality_threshold: 15.0  # Lowered the threshold for quality suggestions to ensure even minor improvements are caught

github:
  labels: [sourcery-auto]  # Labels added to pull requests created by Sourcery
  ignore_labels:
    - sourcery-ignore
  request_review: auto  # Automatically requests reviews for Sourcery PRs
  sourcery_branch: sourcery/{base_branch}

clone_detection:
  min_lines: 2  # Reduced minimum lines to catch smaller duplicated code blocks
  min_duplicates: 2  # Minimum number of occurrences before detecting duplicate code
  identical_clones_only: false  # Detects both identical and similar clones

proxy:
  url: ""
  ssl_certs_file: ""
  no_ssl_verify: false
