name: burton_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
    - flask
    - flask-cors
    - langchain==0.1.11
    - langchain-anthropic==0.1.4
    - langchain-community==0.0.26
    - langchain-core==0.1.29
    - langchain-openai==0.0.8
    - openai==1.43.0
    - anthropic==0.34.1
    - google-generativeai==0.5.4
    - groq==0.11.0
    - pydantic==2.8.2
    - python-dotenv==1.0.1
    - requests==2.31.0
    - langchain-groq==0.1.5
    - langchain-gpt3==0.1.4
